spring:
  application:
    name: gateway
server:
  port: 8888
zuul:
  prefix: /api
  ignored-services: '*'
  routes:
    products:
      path: /ps/**
      serviceId: product-service
    reviews:
      path: /rs/**
      serviceId: review-service
    composite-products:
      path: /cps/**
      serviceId: product-composite-service
sec:
  user:
    name: test
    password: test
logging:
  level:
    com.example.ms.edgeservice.filter: DEBUG