spring:
  application:
    name: gateway
server:
  port: 8888
zuul:
  prefix: /api
  ignored-services: '*'
  routes:
    products:
      path: /ps/**
      serviceId: product-service
    reviews:
      path: /rs/**
      serviceId: review-service
sec:
  user:
    name: test
    password: test
